In [4]:
import pandas as pd

df = pd.read_csv('WHO_AirQuality_Database_2018.csv')
df

,ID WHO city,iso3,country,city,pm10,Year,type_of_stations,pm10_type,pm25,pm25_type,...,latitude_pop,longitude_pop,Region,region_abbr,tempcov_PM10_grad,tempcov_PM25_grad,conc_pm25,color_pm25,conc_pm10,color_pm10
0,3.0,ALB,Albania,Tirana,31.615421,2013,"1 station, traffic, urban",Measured,16.062366,Measured,...,NaN,NaN,Europe (LMIC),Eur (LMIC),NaN,NaN,15-<25,orange,30-<50,darkred
1,15.0,AUS,Australia,Central Coast,12.820462,2014,-,Converted,5.500000,Measured,...,NaN,NaN,Western Pacific (HIC),Wpr (HIC),NaN,NaN,<10,green,<20,green
2,18.0,AUS,Australia,Devonport,14.918356,2013,-,Converted,6.400000,Measured,...,NaN,NaN,Western Pacific (HIC),Wpr (HIC),NaN,NaN,<10,green,<20,green
3,19.0,AUS,Australia,Geelong,17.500000,2014,"1 station, Residential/Light Industry",Measured,7.507530,Converted,...,NaN,NaN,Western Pacific (HIC),Wpr (HIC),NaN,NaN,<10,green,<20,green
4,22.0,AUS,Australia,Hobart,14.219058,2013,-,Converted,6.100000,Measured,...,NaN,NaN,Western Pacific (HIC),Wpr (HIC),NaN,NaN,<10,green,<20,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11966,NaN,SAU,Saudi Arabia,Riyadh,201.000000,2014,1 N.A.,Measured,51.000000,Measured,...,24.690466,46.709566,Eastern Mediterranean (HIC),Emr (HIC),NaN,NaN,>50,darkred,>100,darkred
11967,NaN,SAU,Saudi Arabia,Riyadh,240.000000,2015,1 N.A.,Measured,69.000000,Measured,...,24.690466,46.709566,Eastern Mediterranean (HIC),Emr (HIC),NaN,NaN,>50,darkred,>100,darkred
11968,NaN,SAU,Saudi Arabia,Riyadh,251.000000,2016,1 N.A.,Measured,73.000000,Measured,...,24.690466,46.709566,Eastern Mediterranean (HIC),Emr (HIC),NaN,NaN,>50,darkred,>100,darkred
11969,NaN,SAU,Saudi Arabia,Dammam,260.000000,2015,1 N.A.,Measured,61.000000,Measured,...,26.392666,49.977715,Eastern Mediterranean (HIC),Emr (HIC),NaN,NaN,>50,darkred,>100,darkred
11970,NaN,SAU,Saudi Arabia,Dammam,161.000000,2016,1 N.A.,Measured,56.000000,Measured,...,26.392666,49.977715,Eastern Mediterranean (HIC),Emr (HIC),NaN,NaN,>50,darkred,>100,darkred

In [13]:
unique_countries = df['country'].unique()

dataset = df.copy()
dataset.dropna(inplace=True)
new_unique_countries = dataset['country'].unique()


total_countries = len(unique_countries)

print(f"Всего стран: {total_countries}")
print(f"Приведены данные по всем странам: {total_countries == len(new_unique_countries)}")

Всего стран: 108
Приведены данные по всем странам: False